@urlBase = http://localhost:3000
@user = {{urlBase}}/users
# Para obtener usuarios (GET, sin cuerpo)
@materias = {{urlBase}}/materias


GET {{user}}/
### Para crear usuario (POST, con JSON)
POST {{user}}/
Content-Type: application/json

{
    "dni": "3840384",
    "nombre": "vic",
    "apellido": "Ojeda",
    "mail": "viOj@example.com",
    "contrasena": "vic345678",
    "is_profe": true
}
### Para login (POST, con JSON)
POST {{user}}/login
Content-Type: application/json

{
    "mail": "vicOj@example.com",
    "contrasena": "vic345678"
}

### Obtener datos del usuario autenticado
GET {{user}}/me
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODQwMzg0IiwiaWF0IjoxNzUwODYxMTQyLCJleHAiOjE3NTA4NjQ3NDJ9.wr7TkVDAffgA4C2LIpbetm0VmovwscpP0UqAiIFqMgo


### Obtener todas las materias
GET {{materias}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODQwMzg0IiwiaWF0IjoxNzUwODYxMTQyLCJleHAiOjE3NTA4NjQ3NDJ9.wr7TkVDAffgA4C2LIpbetm0VmovwscpP0UqAiIFqMgo

### Crear una materia
POST {{materias}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODQwMzg0IiwiaWF0IjoxNzUwODYxMTQyLCJleHAiOjE3NTA4NjQ3NDJ9.wr7TkVDAffgA4C2LIpbetm0VmovwscpP0UqAiIFqMgo

{
    "Profesor_ID": "6754839",
    "Nombre": "rdjovjpsdkfz",
    "horario": "lunes"
}

### Obtener mis materias
GET {{materias}}/mias
Authorization: Bearer $2b$10$Wy7T0Mjit5TgITn7WLPv/eGqI6TmXtm0mDKlHQeRsiTz6Fe1NpdzW