@urlBase = http://localhost:3000
@user = {{urlBase}}/users
# Para obtener usuarios (GET, sin cuerpo)
@materias = {{urlBase}}/materias


GET {{user}}/
### Para crear usuario (POST, con JSON)
POST {{user}}/
Content-Type: application/json

{
    "dni": "87458598",
    "nombre": "Noliiiiii",
    "apellido": "Currhu",
    "email": "trbtrb.currhu@example.com",
    "contrasena": "12349876",
    "is_profe": true
}
### Para login (POST, con JSON)
POST {{user}}/login
Content-Type: application/json

{
    "email": "noliii.currhu@example.com",
    "contrasena": "12349876"
}

### Obtener datos del usuario autenticado
GET {{user}}/me
Authorization: bearer $2b$10$Y9vhxgT3ykn8Em2u6OXZi.05Le14ZS4kvVUvsDRsCSARjkK6KkZ7q


### Obtener todas las materias
GET {{materias}}
Authorization: Bearer $2b$10$Y9vhxgT3ykn8Em2u6OXZi.05Le14ZS4kvVUvsDRsCSARjkK6KkZ7q

### Crear una materia
POST {{materias}}
Content-Type: application/json
Authorization: $2b$10$Y9vhxgT3ykn8Em2u6OXZi.05Le14ZS4kvVUvsDRsCSARjkK6KkZ7q

{
    "Profesor_ID": "87458598",
    "Nombre": "Matemáticas Avanzadas",
    "Dia_Horario": "Miercoles 14:15-18:00"
}

### Obtener mis materias
GET {{materias}}/mias
Authorization: Bearer $2b$10$Y9vhxgT3ykn8Em2u6OXZi.05Le14ZS4kvVUvsDRsCSARjkK6KkZ7q